# Generated by Django 4.2.7 on 2023-11-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.CharField(max_length=120)),
                ('company', models.CharField(max_length=225)),
                ('count_immunization', models.IntegerField(default=1)),
                ('description', models.TextField(max_length=1500)),
                ('stock', models.IntegerField(default=0)),
                ('in_holding', models.IntegerField(default=0)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
    ]
