# Generated by Django 4.2.7 on 2023-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='slug',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
