# Generated by Django 4.2.7 on 2023-11-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0002_alter_vaccine_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='count_immunization',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
