# Generated by Django 4.2.7 on 2023-11-19 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0003_alter_vaccine_count_immunization'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vaccine',
            old_name='stock',
            new_name='available',
        ),
    ]
