# Generated by Django 4.0.10 on 2023-11-23 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patientprofile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientprofile',
            old_name='occupaon',
            new_name='occupation',
        ),
    ]
