# Generated by Django 4.2.7 on 2023-11-24 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_occupaon_patientprofile_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='ssn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
