# Generated by Django 4.2.7 on 2023-11-20 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0002_alter_schedulevaccine_nurse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulevaccine',
            name='nurse',
        ),
        migrations.AddField(
            model_name='schedulevaccine',
            name='patient',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': False, 'is_nurse': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
