# Generated by Django 4.2.7 on 2023-11-20 08:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_patientprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_remove_schedulevaccine_nurse_schedulevaccine_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulevaccine',
            name='nurse',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_nurse': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedulevaccine',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patientprofile'),
        ),
    ]
