# Generated by Django 4.2.7 on 2023-11-20 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_schedulevaccine_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulevaccine',
            name='schedule_time',
            field=models.TimeField(default=datetime.datetime(2023, 11, 20, 8, 26, 43, 821457, tzinfo=datetime.timezone.utc)),
        ),
    ]
