# Generated by Django 4.2.7 on 2023-11-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_alter_schedulevaccine_schedule_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulevaccine',
            old_name='schedule',
            new_name='schedule_date',
        ),
    ]
